# Copyright 2018 - Andreas Westerwick <westerwick@pconas.de>
# SPDX-License-Identifier: GPL-3.0-or-later

name:                lsc
version:             0.3.0.2
github:              "foshardware/lsc"
license:             GPL-3
author:              "Andreas Westerwick"
maintainer:          "westerwick@pconas.de"
copyright:           "2019 Andreas Westerwick"
build-type:          Custom

flags:
  glpk:
    default: false
    manual: false
  debug:
    default: false
    manual: false

extra-source-files:
- README.md

custom-setup:
  dependencies:
  - base >= 4.9
  - file-embed
  - Cabal
  - process

dependencies:
- base >= 4.9
- aeson
- array
- arrows
- arrowgant
- async
- bifunctors
- blaze-svg
- blif
- bytestring
- cabal-file-th
- cereal
- concurrent-output
- containers >= 0.5.8
- cond
- data-default
- deepseq
- directory
- dir-traverse
- entropy
- file-embed
- filepath
- firrtl
- haddock-api
- hashable
- hashtables
- kan-extensions
- lefdef
- lens
- linear
- matrix
- mmorph
- monad-loops
- mtl
- mwc-random
- parallel
- parsec
- parsec-numbers
- pointed
- pretty-terminal
- primitive
- process
- SafeSemaphore
- silently
- split
- foldl
- foldl-statistics
- tasty
- tasty-hunit
- tasty-quickcheck
- template-haskell
- text
- time
- unordered-containers
- vector
- vector-algorithms
- verilog

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -O2
  when:
  - condition: flag(glpk)
    dependencies:
    - glpk-hs
    cpp-options:
    - -DGLPK
  - condition: flag(debug)
    cpp-options:
    - -DDEBUG
    ghc-options:
    - -g
    - -dcore-lint
    - -ddump-simpl
    - -fforce-recomp
    - -debug

executables:
  lsc:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - lsc
    ghc-options:
    - -Wall
    - -rtsopts
    - -threaded
    - -O2
    when:
    - condition: flag(debug)
      cpp-options:
      - -DDEBUG
      ghc-options:
      - -g
      - -dcore-lint
      - -ddump-simpl
      - -fforce-recomp
      - -debug

  lsc-doc:
    main:                Evid.hs
    source-dirs:         doc
    dependencies:
    - lsc
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -dynamic

tests:
  lsc-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - lsc
    ghc-options:
    - -Wall
    - -rtsopts
    - -threaded
    - -O2
    - -dynamic
    when:
    - condition: flag(debug)
      cpp-options:
      - -DDEBUG
      ghc-options:
      - -g
      - -dcore-lint
      - -debug

