# Copyright 2018 - Andreas Westerwick <westerwick@pconas.de>
# SPDX-License-Identifier: GPL-3.0-or-later

name:                lsc
version:             0.2.1.1
github:              "foshardware/lsc"
license:             GPL-3
author:              "Andreas Westerwick"
maintainer:          "westerwick@pconas.de"
copyright:           "2019 Andreas Westerwick"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- aeson
- array
- arrowgant
- async
- base16-bytestring
- blaze-svg
- blif
- bytestring
- cabal-file-th
- cereal
- concurrent-output
- containers
- cond
- data-default
- data-default-class
- def
- entropy
- file-embed
- filepath
- firrtl
- hashable
- hashtables
- kan-extensions
- lef
- lens
- linear
- matrix
- mmorph
- monad-loops
- mtl
- mwc-random
- parallel
- parsec
- parsec-numbers
- primitive
- random
- SafeSemaphore
- split
- template-haskell
- text
- time
- transformers
- unordered-containers
- vector
- vector-algorithms
- verilog


library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -O2

executables:
  lsc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lsc

tests:
  lsc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -O
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lsc
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - lens
    - data-default
    - unordered-containers
